export const pythonData = [
  {
    id: 1,
    title: "Learning Python for Data Analysis and Visualization",
    author: "Jose Portilla",
    rate: "",
    price: 119.99,
    bestseller: true,
    onSale: true,
  },
  {
    id: 2,
    title: "Python for Beginners - Learn Programming from scratch",
    author: "Edwin Diaz, Coding Faculty Solutions",
    rate: "",
    price: 104.99,
    bestseller: false,
    onSale: true,
  },
  {
    id: 3,
    title: "Learn Python: Python for Beginners",
    author: "Abrar Hussain",
    rate: "",
    price: 100.99,
    bestseller: false,
    onSale: false,
  },
  {
    id: 4,
    title: "Python for Data Structures, Algorithms, and Interviews!",
    author: "Jose Portilla",
    rate: "",
    price: 120.99,
    bestseller: true,
    onSale: true,
  },
  {
    id: 5,
    title: "Automate the Boring Stuff with Python Programming",
    author: "Al Sweigart",
    rate: "",
    price: 54.99,
    bestseller: false,
    onSale: true,
  },
  {
    id: 6,
    title: "Python 3 For Offensive PenTest: A Complete Practical Course",
    author: "Jose Portilla",
    rate: "",
    price: 119.99,
    bestseller: true,
    onSale: true,
  },
  {
    id: 7,
    title: "Taming Big Data with Apache Spark and Python - Hands On!",
    author: "Sundog Education",
    rate: "",
    price: 149.99,
    bestseller: true,
    onSale: true,
  },
];
export const js = [
  {
    id: 1,
    title: "Javascript for Beginners",
    author: "Framework Tech Media",
    rate: "",
    price: 24.99,
    bestseller: false,
    onSale: false,
  },
  {
    id: 2,
    title: "1 Hour JavaScript",
    author: "John Bura",
    rate: "",
    price: 104.99,
    bestseller: false,
    onSale: true,
  },
  {
    id: 3,
    title: "JavaScript Understanding the Weird Parts",
    author: "Anthony Alicea",
    rate: "",
    price: 100.99,
    bestseller: false,
    onSale: true,
  },
  {
    id: 4,
    title: "Javascript for Beginners Learn by Doing Practical Exercises",
    author: "Edwin Diaz",
    rate: "",
    price: 120.99,
    bestseller: false,
    onSale: true,
  },
  {
    id: 5,
    title: "Automate the Boring Stuff with JS Programming",
    author: "Al Sweigart",
    rate: "",
    price: 54.99,
    bestseller: false,
    onSale: true,
  },
  {
    id: 6,
    title: "JavaScript from Beginner to Expert",
    author: "Arkadiusz Wlodarczyk",
    rate: "",
    price: 119.99,
    bestseller: true,
    onSale: true,
  },
  {
    id: 7,
    title: "JavaScript for Kids: Code Your Own Games and Apps at Any Age",
    author: "Bryson Payne",
    rate: "",
    price: 24.99,
    bestseller: false,
    onSale: true,
  },
];
