export const pythonData = [
  {
    id: 1,
    title: "Learning Python for Data Analysis and Visualization",
    author: "Jose Portilla",
    rate: 4.7,
    price: 119.99,
    bestseller: true,
    onSale: true,
    review: 123.45,
  },
  {
    id: 2,
    title: "Python for Beginners - Learn Programming from scratch",
    author: "Edwin Diaz, Coding Faculty Solutions",
    rate: 4.6,
    price: 104.99,
    bestseller: false,
    onSale: true,
    review: 1223.45,
  },
  {
    id: 3,
    title: "Learn Python: Python for Beginners",
    author: "Abrar Hussain",
    rate: 4,
    price: 100.99,
    bestseller: false,
    onSale: false,
    review: 223.45,
  },
  {
    id: 4,
    title: "Python for Data Structures, Algorithms, and Interviews!",
    author: "Jose Portilla",
    rate: 4.7,
    price: 120.99,
    bestseller: true,
    onSale: true,
    review: 1223.98,
  },
  {
    id: 5,
    title: "Automate the Boring Stuff with Python Programming",
    author: "Al Sweigart",
    rate: 4.5,
    price: 54.99,
    bestseller: false,
    onSale: true,
    review: 778.09,
  },
  {
    id: 6,
    title: "Python 3 For Offensive PenTest: A Complete Practical Course",
    author: "Jose Portilla",
    rate: 4.6,
    price: 119.99,
    bestseller: true,
    onSale: true,
    review: 1990.08,
  },
  {
    id: 7,
    title: "Taming Big Data with Apache Spark and Python - Hands On!",
    author: "Sundog Education",
    rate: 4.7,
    price: 149.99,
    bestseller: true,
    onSale: true,
    review: 4556.09,
  },
];
export const js = [
  {
    id: 1,
    title: "Javascript for Beginners",
    author: "Framework Tech Media",
    rate: 4.5,
    price: 24.99,
    bestseller: false,
    onSale: false,
    review: 1233.9,
  },
  {
    id: 2,
    title: "1 Hour JavaScript",
    author: "John Bura",
    rate: 4.7,
    price: 104.99,
    bestseller: false,
    onSale: true,
    review: 11987.09,
  },
  {
    id: 3,
    title: "JavaScript Understanding the Weird Parts",
    author: "Anthony Alicea",
    rate: 4.4,
    price: 100.99,
    bestseller: false,
    onSale: true,
    review: 435.98,
  },
  {
    id: 4,
    title: "Javascript for Beginners Learn by Doing Practical Exercises",
    author: "Edwin Diaz",
    rate: 4.9,
    price: 120.99,
    bestseller: false,
    onSale: true,
    review: 654.87,
  },
  {
    id: 5,
    title: "Automate the Boring Stuff with JS Programming",
    author: "Al Sweigart",
    rate: 4.6,
    price: 54.99,
    bestseller: false,
    onSale: true,
    review: 908.98,
  },
  {
    id: 6,
    title: "JavaScript from Beginner to Expert",
    author: "Arkadiusz Wlodarczyk",
    rate: 4.4,
    price: 119.99,
    bestseller: true,
    onSale: true,
    review: 213.98,
  },
  {
    id: 7,
    title: "JavaScript for Kids: Code Your Own Games and Apps at Any Age",
    author: "Bryson Payne",
    rate: 4.3,
    price: 24.99,
    bestseller: false,
    onSale: true,
    review: 3373.98,
  },
];
export const excel = [
  {
    id: 1,
    title: "Microsoft Excel - From Beginner to Expert in 6 Hours",
    author: "Todd McLeod",
    rate: 4.7,
    price: 24.99,
    bestseller: false,
    onSale: false,
    review: 199.98,
  },
  {
    id: 2,
    title: "1 Hour JavaScript",
    author: "John Bura",
    rate: 4.3,
    price: 104.99,
    bestseller: false,
    onSale: true,
    review: 111.98,
  },
  {
    id: 3,
    title: "JavaScript Understanding the Weird Parts",
    author: "Anthony Alicea",
    rate: 4.2,
    price: 100.99,
    bestseller: false,
    onSale: true,
    review: 467.67,
  },
  {
    id: 4,
    title: "Javascript for Beginners Learn by Doing Practical Exercises",
    author: "Edwin Diaz",
    rate: 4,
    price: 120.99,
    bestseller: false,
    onSale: true,
    review: 657.66,
  },
  {
    id: 5,
    title: "Automate the Boring Stuff with JS Programming",
    author: "Al Sweigart",
    rate: 4.8,
    price: 54.99,
    bestseller: false,
    onSale: true,
    review: 443.44,
  },
  {
    id: 6,
    title: "JavaScript from Beginner to Expert",
    author: "Arkadiusz Wlodarczyk",
    rate: 4.7,
    price: 119.99,
    bestseller: true,
    onSale: true,
    review: 776.77,
  },
  {
    id: 7,
    title: "JavaScript for Kids: Code Your Own Games and Apps at Any Age",
    author: "Bryson Payne",
    rate: 4.7,
    price: 24.99,
    bestseller: false,
    onSale: true,
    review: 667.32,
  },
];
export const aws = [
  {
    id: 1,
    title: "Amazon Web Services (AWS) Certified 2022 - 4 Certifications!",
    author: "Paul Coady",
    rate: 4.5,
    price: 149.99,
    bestseller: false,
    onSale: true,
    review: 4556.65,
  },
  {
    id: 2,
    title: "AWS Certified Security Specialty 2022",
    author: "Zeal Vora",
    rate: 4.7,
    price: 39.99,
    bestseller: true,
    onSale: false,
    review: 456.32,
  },
  {
    id: 3,
    title: "Part 1: AWS Certified Solutions Architect SAA C02",
    author: "Lingam",
    rate: 4.5,
    price: 99.99,
    bestseller: false,
    onSale: true,
    review: 345.87,
  },
  {
    id: 4,
    title: "Practice Test AWS Solutions Architect Associate SAA C02",
    author: "Lingam",
    rate: 4.7,
    price: 54.99,
    bestseller: false,
    onSale: true,
    review: 435.64,
  },
  {
    id: 5,
    title: "Part 2: AWS Certified Solutions Architect SAA C02",
    author: "Lingam",
    rate: 4.7,
    price: 99.99,
    bestseller: false,
    onSale: true,
    review: 334.3,
  },
  {
    id: 6,
    title: "AWS Certified Solutions Architect - Associate 2022",
    author: "Alan Rodrigues",
    rate: 4.9,
    price: 119.99,
    bestseller: false,
    onSale: true,
    review: 213.4,
  },
  {
    id: 7,
    title: "AWS Certified Solutions Architect - Associate 2022",
    author: "Zeal Vora",
    rate: 4,
    price: 34.99,
    bestseller: false,
    onSale: false,
    review: 123.4,
  },
];
export const dataScience = [
  {
    id: 1,
    title: "Data Science A-Z™: Real-Life Data Science Exercises Included",
    author: "Kirill Ereme",
    rate: 4.7,
    price: 24.99,
    bestseller: false,
    onSale: false,
    review: 223.45,
  },
  {
    id: 2,
    title: "Machine Learning, Data Science and Deep Learning with Python",
    author: "Frank Kane",
    rate: 4.9,
    price: 16.99,
    bestseller: false,
    onSale: true,
    review: 997.04,
  },
  {
    id: 3,
    title: "Data Science: Deep Learning and Neural Networks in Python",
    author: "Lazy Programmer Inc.",
    rate: 4,
    price: 169.99,
    bestseller: false,
    onSale: true,
    review: 4223.65,
  },
  {
    id: 4,
    title: "R Programming A-Z™: R For Data Science With Real Exercises!",
    author: "Kirill Ereme",
    rate: 4,
    price: 199.99,
    bestseller: true,
    onSale: true,
    review: 2223.03,
  },
  {
    id: 5,
    title: "Data Science and Machine Learning Bootcamp with R",
    author: "Al Sweigart",
    rate: 4.1,
    price: 199.99,
    bestseller: false,
    onSale: true,
    review: 5223.01,
  },
  {
    id: 6,
    title: "R Programming: Advanced Analytics In R For Data Science",
    author: "Kirill Ereme",
    rate: 4.7,
    price: 119.99,
    bestseller: false,
    onSale: true,
    review: 45223.43,
  },
  {
    id: 7,
    title: "Python for Data Science and Machine Learning Bootcamp",
    author: "Jose Portilla",
    rate: "4.6",
    price: 199.99,
    bestseller: false,
    onSale: true,
    review: 5223.07,
  },
];
